name: StaffToggle
version: 1.1.2
main: uk.co.arcator.stafftoggle.StaffToggle
api-version: 1.16
depend:
  - LuckPerms
commands:
  staff:
    usage: /staff
    description: toggle staff mode
    permission: stafftoggle.toggle
    aliases:
      - st
      - stafftoggle
libraries:
  - org.jetbrains.kotlin:kotlin-stdlib:1.8.0
